<script setup lang="ts">
import { computed } from 'vue'

interface ImageGridColumnProps {
  value: any
  imageWidth?: string | number | null
  imageHeight?: string | number | null
  square?: boolean
  circular?: boolean
  stacked?: boolean
  ring?: number
  overlap?: number
  limit?: number | null
  limitedRemainingText?: boolean
  limitedRemainingTextSize?: string
  wrap?: boolean
  disk?: string | null
  visibility?: string | null
  defaultImageUrl?: string | null
  checkFileExistence?: boolean
  extraImgAttributes?: Record<string, any>
  description?: string | null
  descriptionPosition?: 'above' | 'below'
}

const props = withDefaults(defineProps<ImageGridColumnProps>(), {
  imageWidth: null,
  imageHeight: null,
  square: false,
  circular: false,
  stacked: false,
  ring: 3,
  overlap: 4,
  limit: null,
  limitedRemainingText: false,
  limitedRemainingTextSize: 'sm',
  wrap: false,
  disk: null,
  visibility: null,
  defaultImageUrl: null,
  checkFileExistence: true,
  extraImgAttributes: () => ({}),
  description: null,
  descriptionPosition: 'below',
})

const images = computed(() => {
  if (!props.value) return []
  return Array.isArray(props.value) ? props.value : [props.value]
})

const displayImages = computed(() => {
  if (!props.limit) return images.value
  return images.value.slice(0, props.limit)
})

const remainingCount = computed(() => {
  if (!props.limit || images.value.length <= props.limit) return 0
  return images.value.length - props.limit
})

const sizeStyle = computed(() => {
  const style: Record<string, string> = {}

  if (props.imageWidth) {
    style.width = typeof props.imageWidth === 'number' ? `${props.imageWidth}px` : props.imageWidth
  }

  if (props.imageHeight) {
    style.height = typeof props.imageHeight === 'number' ? `${props.imageHeight}px` : props.imageHeight
  }

  return style
})

const shapeClass = computed(() => {
  if (props.circular) return 'rounded-full'
  if (props.square) return 'aspect-square'
  return 'rounded-md'
})

const ringClass = computed(() => {
  const ringMap: Record<number, string> = {
    0: 'ring-0',
    1: 'ring-1',
    2: 'ring-2',
    3: 'ring',
    4: 'ring-4',
    5: 'ring-[5px]',
    6: 'ring-[6px]',
    7: 'ring-[7px]',
    8: 'ring-8',
  }
  return ringMap[props.ring] || 'ring'
})

const overlapClass = computed(() => {
  // Negative margin for overlap
  const overlapMap: Record<number, string> = {
    0: '',
    1: '-ml-1',
    2: '-ml-2',
    3: '-ml-3',
    4: '-ml-4',
    5: '-ml-5',
    6: '-ml-6',
    7: '-ml-7',
    8: '-ml-8',
  }
  return overlapMap[props.overlap] || '-ml-4'
})

const remainingSizeClass = computed(() => {
  const sizeMap: Record<string, string> = {
    'xs': 'text-xs',
    'sm': 'text-sm',
    'md': 'text-base',
    'lg': 'text-lg',
    'xl': 'text-xl',
  }
  return sizeMap[props.limitedRemainingTextSize] || 'text-sm'
})

const getImageUrl = (image: string): string => {
  // If it's already an absolute URL, return it
  if (image.startsWith('http://') || image.startsWith('https://') || image.startsWith('data:')) {
    return image
  }

  // Handle disk and visibility for Laravel storage
  // If visibility is 'public' or disk is 'public', use /storage/ path
  // Otherwise, this should be a temporary URL generated by the backend
  if (props.visibility === 'public' || props.disk === 'public') {
    return `/storage/${image}`
  }

  // For non-public storage, assume the backend will provide temporary URLs
  // If it's a relative path, prepend /storage/ as default
  if (!image.startsWith('/')) {
    return `/storage/${image}`
  }

  return image
}

const handleImageError = (event: Event) => {
  if (props.defaultImageUrl) {
    (event.target as HTMLImageElement).src = props.defaultImageUrl
  }
}
</script>

<template>
  <div class="flex flex-col gap-1">
    <!-- Description above -->
    <div v-if="description && descriptionPosition === 'above'" class="text-[11px] text-muted-foreground/70">
      {{ description }}
    </div>

    <!-- Main content -->
    <div :class="wrap ? 'flex flex-wrap gap-1.5' : 'flex items-center'">
      <!-- Stacked images -->
      <div v-if="stacked" class="flex items-center">
        <div
          v-for="(image, index) in displayImages"
          :key="index"
          :class="[
            'relative',
            index > 0 && overlapClass,
          ]"
        >
          <img
            :src="getImageUrl(image)"
            :alt="`Image ${index + 1}`"
            :style="sizeStyle"
            :class="[
              shapeClass,
              ringClass,
              'ring-background object-cover',
            ]"
            v-bind="extraImgAttributes"
            @error="handleImageError"
          />
        </div>

        <span
          v-if="limitedRemainingText && remainingCount > 0"
          :class="[
            'ml-2 text-muted-foreground font-medium',
            remainingSizeClass,
          ]"
        >
          +{{ remainingCount }}
        </span>
      </div>

      <!-- Regular images -->
      <template v-else>
        <img
          v-for="(image, index) in displayImages"
          :key="index"
          :src="getImageUrl(image)"
          :alt="`Image ${index + 1}`"
          :style="sizeStyle"
          :class="[
            shapeClass,
            'object-cover',
          ]"
          v-bind="extraImgAttributes"
          @error="handleImageError"
        />

        <span
          v-if="limitedRemainingText && remainingCount > 0"
          :class="[
            'text-muted-foreground font-medium',
            remainingSizeClass,
          ]"
        >
          +{{ remainingCount }}
        </span>
      </template>
    </div>

    <!-- Description below -->
    <div v-if="description && descriptionPosition === 'below'" class="text-[11px] text-muted-foreground/70">
      {{ description }}
    </div>
  </div>
</template>
